server {
    listen 80;
    listen [::]:80;
    server_name ytm.lushmedia.net;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://ytm.lushmedia.net$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ytm.lushmedia.net;
    ssl_certificate /etc/letsencrypt/live/ytm.lushmedia.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ytm.lushmedia.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 20m;

    location / {
        proxy_pass http://127.0.0.1:8015;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
